name: todooo
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  animated_text_kit: ^4.2.2
  gif: ^2.3.0

  table_calendar: ^3.2.0
  provider: ^6.1.2
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  flutter_local_notifications: ^19.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - lib/images/

